# Generated by Django 4.2.7 on 2023-12-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoncard',
            name='attack',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
