# Generated by Django 4.2.7 on 2023-12-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0002_alter_pokemoncard_attack_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemoncard',
            name='card_type',
            field=models.CharField(choices=[('Fire', 'Fire'), ('Water', 'Water'), ('Grass', 'Grass'), ('Electric', 'Electric'), ('Psychic', 'Psychic'), ('Fighting', 'Fighting'), ('Dark', 'Dark'), ('Steel', 'Steel'), ('Fairy', 'Fairy'), ('Dragon', 'Dragon'), ('Normal', 'Normal'), ('Ghost', 'Ghost'), ('Ice', 'Ice'), ('Bug', 'Bug'), ('Rock', 'Rock'), ('Ground', 'Ground'), ('Poison', 'Poison'), ('Flying', 'Flying')], default='none', max_length=255),
        ),
    ]
