# Generated by Django 4.2.7 on 2023-12-15 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardquest', '0003_collection_release_date_alter_pokemoncard_card_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='release_date',
            new_name='collection_date',
        ),
    ]
